"""treasury

Revision ID: 58c617fdc434
Revises: 17fb731671a7
Create Date: 2026-01-25 17:40:30.183789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '58c617fdc434'
down_revision: Union[str, Sequence[str], None] = '17fb731671a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blockchain_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('contract_address', sa.String(length=42), nullable=False),
    sa.Column('event_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('transaction_hash', sa.String(length=66), nullable=False),
    sa.Column('block_number', sa.Integer(), nullable=False),
    sa.Column('block_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('log_index', sa.Integer(), nullable=False),
    sa.Column('processed', sa.Boolean(), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transaction_hash', 'log_index', name='uq_tx_log')
    )
    op.create_index(op.f('ix_blockchain_events_block_number'), 'blockchain_events', ['block_number'], unique=False)
    op.create_index(op.f('ix_blockchain_events_contract_address'), 'blockchain_events', ['contract_address'], unique=False)
    op.create_index(op.f('ix_blockchain_events_event_type'), 'blockchain_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_blockchain_events_id'), 'blockchain_events', ['id'], unique=False)
    op.create_index(op.f('ix_blockchain_events_processed'), 'blockchain_events', ['processed'], unique=False)
    op.create_table('daily_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('total_token_holders', sa.Integer(), nullable=False),
    sa.Column('active_token_holders', sa.Integer(), nullable=False),
    sa.Column('total_funds', sa.Integer(), nullable=False),
    sa.Column('active_funds', sa.Integer(), nullable=False),
    sa.Column('funds_in_retirement', sa.Integer(), nullable=False),
    sa.Column('total_deposits_today', sa.DECIMAL(precision=18, scale=6), nullable=False),
    sa.Column('total_withdrawals_today', sa.DECIMAL(precision=18, scale=6), nullable=False),
    sa.Column('total_fees_today', sa.DECIMAL(precision=18, scale=6), nullable=False),
    sa.Column('total_tvl', sa.DECIMAL(precision=18, scale=6), nullable=False),
    sa.Column('active_proposals', sa.Integer(), nullable=False),
    sa.Column('votes_cast_today', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('total_token_holders >= 0', name='check_token_holders_positive'),
    sa.CheckConstraint('total_tvl >= 0', name='check_tvl_positive'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_daily_snapshots_date', 'daily_snapshots', ['snapshot_date'], unique=False, postgresql_using='btree')
    op.create_index(op.f('ix_daily_snapshots_id'), 'daily_snapshots', ['id'], unique=False)
    op.create_index(op.f('ix_daily_snapshots_snapshot_date'), 'daily_snapshots', ['snapshot_date'], unique=True)
    op.create_table('defi_protocols',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('protocol_address', sa.String(length=42), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('apy', sa.Integer(), nullable=False),
    sa.Column('risk_level', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('total_deposited', sa.DECIMAL(precision=18, scale=6), nullable=True),
    sa.Column('added_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint('risk_level BETWEEN 1 AND 3', name='check_risk_level'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_defi_protocols_id'), 'defi_protocols', ['id'], unique=False)
    op.create_index(op.f('ix_defi_protocols_is_active'), 'defi_protocols', ['is_active'], unique=False)
    op.create_index(op.f('ix_defi_protocols_protocol_address'), 'defi_protocols', ['protocol_address'], unique=True)
    op.create_index(op.f('ix_defi_protocols_verified'), 'defi_protocols', ['verified'], unique=False)
    op.create_table('monthly_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('total_users_end_of_month', sa.Integer(), nullable=True),
    sa.Column('new_users_this_month', sa.Integer(), nullable=True),
    sa.Column('total_funds_end_of_month', sa.Integer(), nullable=True),
    sa.Column('new_funds_this_month', sa.Integer(), nullable=True),
    sa.Column('funds_in_retirement', sa.Integer(), nullable=True),
    sa.Column('total_deposits_month', sa.DECIMAL(precision=18, scale=6), nullable=True),
    sa.Column('total_withdrawals_month', sa.DECIMAL(precision=18, scale=6), nullable=True),
    sa.Column('total_fees_collected', sa.DECIMAL(precision=18, scale=6), nullable=True),
    sa.Column('avg_tvl_month', sa.DECIMAL(precision=18, scale=6), nullable=True),
    sa.Column('ending_tvl', sa.DECIMAL(precision=18, scale=6), nullable=True),
    sa.Column('tokens_burned', sa.Integer(), nullable=True),
    sa.Column('tokens_renewed', sa.Integer(), nullable=True),
    sa.Column('proposals_created', sa.Integer(), nullable=True),
    sa.Column('proposals_executed', sa.Integer(), nullable=True),
    sa.Column('total_votes_cast', sa.Integer(), nullable=True),
    sa.Column('user_growth_rate', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('tvl_growth_rate', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('month BETWEEN 1 AND 12', name='check_valid_month'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('year', 'month', name='uq_year_month')
    )
    op.create_index('idx_monthly_reports_date', 'monthly_reports', ['year', 'month'], unique=False)
    op.create_index(op.f('ix_monthly_reports_id'), 'monthly_reports', ['id'], unique=False)
    op.create_index(op.f('ix_monthly_reports_month'), 'monthly_reports', ['month'], unique=False)
    op.create_index(op.f('ix_monthly_reports_year'), 'monthly_reports', ['year'], unique=False)
    op.create_table('system_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('metric_name', sa.String(length=100), nullable=False),
    sa.Column('metric_value', sa.DECIMAL(precision=18, scale=6), nullable=False),
    sa.Column('metric_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_system_metrics_name', 'system_metrics', ['metric_name'], unique=False)
    op.create_index('idx_system_metrics_updated', 'system_metrics', ['last_updated'], unique=False)
    op.create_index(op.f('ix_system_metrics_id'), 'system_metrics', ['id'], unique=False)
    op.create_index(op.f('ix_system_metrics_last_updated'), 'system_metrics', ['last_updated'], unique=False)
    op.create_index(op.f('ix_system_metrics_metric_name'), 'system_metrics', ['metric_name'], unique=True)
    op.create_table('token_monthly_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('total_burned', sa.DECIMAL(precision=78, scale=18), nullable=False),
    sa.Column('total_renewed', sa.DECIMAL(precision=78, scale=18), nullable=False),
    sa.Column('holders_burned', sa.Integer(), nullable=False),
    sa.Column('holders_renewed', sa.Integer(), nullable=False),
    sa.Column('burn_executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('renew_executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_year_month', 'token_monthly_stats', ['year', 'month'], unique=True)
    op.create_index(op.f('ix_token_monthly_stats_id'), 'token_monthly_stats', ['id'], unique=False)
    op.create_index(op.f('ix_token_monthly_stats_month'), 'token_monthly_stats', ['month'], unique=False)
    op.create_index(op.f('ix_token_monthly_stats_year'), 'token_monthly_stats', ['year'], unique=False)
    op.create_table('treasury_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('total_balance', sa.DECIMAL(precision=18, scale=6), nullable=False),
    sa.Column('total_fees_collected_usdc', sa.DECIMAL(precision=18, scale=6), nullable=False),
    sa.Column('total_fees_collected_all_time', sa.DECIMAL(precision=18, scale=6), nullable=False),
    sa.Column('total_fees_withdrawn', sa.DECIMAL(precision=18, scale=6), nullable=False),
    sa.Column('total_funds_registered', sa.Integer(), nullable=False),
    sa.Column('active_funds_count', sa.Integer(), nullable=False),
    sa.Column('total_early_retirement_requests', sa.Integer(), nullable=False),
    sa.Column('pending_requests_count', sa.Integer(), nullable=False),
    sa.Column('approved_early_retirements', sa.Integer(), nullable=False),
    sa.Column('rejected_early_retirements', sa.Integer(), nullable=False),
    sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('total_balance >= 0', name='check_treasury_balance_positive'),
    sa.CheckConstraint('total_fees_collected_usdc >= 0', name='check_fees_positive'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_treasury_stats_updated', 'treasury_stats', ['last_updated'], unique=False)
    op.create_index(op.f('ix_treasury_stats_id'), 'treasury_stats', ['id'], unique=False)
    op.create_index(op.f('ix_treasury_stats_last_updated'), 'treasury_stats', ['last_updated'], unique=False)
    op.create_table('weekly_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('week_number', sa.Integer(), nullable=False),
    sa.Column('week_start_date', sa.Date(), nullable=False),
    sa.Column('week_end_date', sa.Date(), nullable=False),
    sa.Column('avg_daily_active_holders', sa.Integer(), nullable=True),
    sa.Column('avg_daily_tvl', sa.DECIMAL(precision=18, scale=6), nullable=True),
    sa.Column('total_deposits_week', sa.DECIMAL(precision=18, scale=6), nullable=True),
    sa.Column('total_withdrawals_week', sa.DECIMAL(precision=18, scale=6), nullable=True),
    sa.Column('total_fees_week', sa.DECIMAL(precision=18, scale=6), nullable=True),
    sa.Column('new_funds_created', sa.Integer(), nullable=True),
    sa.Column('funds_started_retirement', sa.Integer(), nullable=True),
    sa.Column('proposals_created', sa.Integer(), nullable=True),
    sa.Column('total_votes_cast', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('year', 'week_number', name='uq_year_week')
    )
    op.create_index('idx_weekly_reports_date', 'weekly_reports', ['year', 'week_number'], unique=False)
    op.create_index(op.f('ix_weekly_reports_id'), 'weekly_reports', ['id'], unique=False)
    op.create_index(op.f('ix_weekly_reports_week_number'), 'weekly_reports', ['week_number'], unique=False)
    op.create_index(op.f('ix_weekly_reports_year'), 'weekly_reports', ['year'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('notification_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('related_entity_type', sa.String(length=50), nullable=True),
    sa.Column('related_entity_id', sa.Integer(), nullable=True),
    sa.Column('read', sa.Boolean(), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_notifications_unread', 'notifications', ['user_id', 'read'], unique=False, postgresql_where=sa.text('read = false'))
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index(op.f('ix_notifications_read'), 'notifications', ['read'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('personal_funds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('fund_address', sa.String(length=42), nullable=False),
    sa.Column('owner_address', sa.String(length=42), nullable=False),
    sa.Column('total_deposited', sa.DECIMAL(precision=18, scale=6), nullable=False),
    sa.Column('total_withdrawn', sa.DECIMAL(precision=18, scale=6), nullable=False),
    sa.Column('current_balance', sa.DECIMAL(precision=18, scale=6), nullable=False),
    sa.Column('total_fees_paid', sa.DECIMAL(precision=18, scale=6), nullable=False),
    sa.Column('total_invested', sa.DECIMAL(precision=18, scale=6), nullable=False),
    sa.Column('total_earnings', sa.DECIMAL(precision=18, scale=6), nullable=False),
    sa.Column('timelock_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('retirement_started', sa.Boolean(), nullable=False),
    sa.Column('retirement_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('early_retirement_approved', sa.Boolean(), nullable=False),
    sa.Column('early_retirement_penalty', sa.DECIMAL(precision=18, scale=6), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_locked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_deposit_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_withdrawal_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_compound_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('creation_tx_hash', sa.String(length=66), nullable=False),
    sa.Column('creation_block_number', sa.Integer(), nullable=False),
    sa.CheckConstraint('current_balance >= 0', name='check_balance_positive'),
    sa.CheckConstraint('total_deposited >= 0', name='check_deposits_positive'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_personal_funds_active', 'personal_funds', ['is_active'], unique=False)
    op.create_index('idx_personal_funds_address', 'personal_funds', ['fund_address'], unique=False)
    op.create_index('idx_personal_funds_owner', 'personal_funds', ['owner_id'], unique=False)
    op.create_index('idx_personal_funds_retirement', 'personal_funds', ['retirement_started'], unique=False)
    op.create_index(op.f('ix_personal_funds_fund_address'), 'personal_funds', ['fund_address'], unique=True)
    op.create_index(op.f('ix_personal_funds_id'), 'personal_funds', ['id'], unique=False)
    op.create_index(op.f('ix_personal_funds_is_active'), 'personal_funds', ['is_active'], unique=False)
    op.create_index(op.f('ix_personal_funds_owner_address'), 'personal_funds', ['owner_address'], unique=False)
    op.create_index(op.f('ix_personal_funds_owner_id'), 'personal_funds', ['owner_id'], unique=True)
    op.create_index(op.f('ix_personal_funds_retirement_started'), 'personal_funds', ['retirement_started'], unique=False)
    op.create_table('proposals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proposal_id', sa.Integer(), nullable=False),
    sa.Column('proposer_id', sa.Integer(), nullable=True),
    sa.Column('proposer_address', sa.String(length=42), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('proposal_type', sa.Integer(), nullable=False),
    sa.Column('target_address', sa.String(length=42), nullable=True),
    sa.Column('target_value', sa.DECIMAL(precision=18, scale=6), nullable=True),
    sa.Column('votes_for', sa.DECIMAL(precision=78, scale=18), nullable=True),
    sa.Column('votes_against', sa.DECIMAL(precision=78, scale=18), nullable=True),
    sa.Column('quorum_reached', sa.Boolean(), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('execution_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('executed', sa.Boolean(), nullable=True),
    sa.Column('cancelled', sa.Boolean(), nullable=True),
    sa.Column('transaction_hash', sa.String(length=66), nullable=False),
    sa.Column('block_number', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['proposer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proposals_cancelled'), 'proposals', ['cancelled'], unique=False)
    op.create_index(op.f('ix_proposals_end_time'), 'proposals', ['end_time'], unique=False)
    op.create_index(op.f('ix_proposals_executed'), 'proposals', ['executed'], unique=False)
    op.create_index(op.f('ix_proposals_id'), 'proposals', ['id'], unique=False)
    op.create_index(op.f('ix_proposals_proposal_id'), 'proposals', ['proposal_id'], unique=True)
    op.create_index(op.f('ix_proposals_proposal_type'), 'proposals', ['proposal_type'], unique=False)
    op.create_index(op.f('ix_proposals_proposer_address'), 'proposals', ['proposer_address'], unique=False)
    op.create_index(op.f('ix_proposals_start_time'), 'proposals', ['start_time'], unique=False)
    op.create_table('token_activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('wallet_address', sa.String(length=42), nullable=False),
    sa.Column('activity_type', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('transaction_hash', sa.String(length=66), nullable=True),
    sa.Column('block_number', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_token_activities_activity_type'), 'token_activities', ['activity_type'], unique=False)
    op.create_index(op.f('ix_token_activities_created_at'), 'token_activities', ['created_at'], unique=False)
    op.create_index(op.f('ix_token_activities_id'), 'token_activities', ['id'], unique=False)
    op.create_index(op.f('ix_token_activities_user_id'), 'token_activities', ['user_id'], unique=False)
    op.create_table('token_holders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('wallet_address', sa.String(length=42), nullable=False),
    sa.Column('balance', sa.DECIMAL(precision=78, scale=18), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('has_activity_this_month', sa.Boolean(), nullable=True),
    sa.Column('last_activity_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_activity_type', sa.String(length=64), nullable=True),
    sa.Column('burned_this_month', sa.Boolean(), nullable=True),
    sa.Column('renewed_this_month', sa.Boolean(), nullable=True),
    sa.Column('total_burns', sa.Integer(), nullable=True),
    sa.Column('total_renews', sa.Integer(), nullable=True),
    sa.Column('holder_since', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_token_holders_has_activity_this_month'), 'token_holders', ['has_activity_this_month'], unique=False)
    op.create_index(op.f('ix_token_holders_id'), 'token_holders', ['id'], unique=False)
    op.create_index(op.f('ix_token_holders_is_active'), 'token_holders', ['is_active'], unique=False)
    op.create_index(op.f('ix_token_holders_wallet_address'), 'token_holders', ['wallet_address'], unique=True)
    op.create_table('user_activity_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('wallet_address', sa.String(length=42), nullable=False),
    sa.Column('activity_type', sa.String(length=50), nullable=False),
    sa.Column('activity_category', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('related_entity_type', sa.String(length=50), nullable=True),
    sa.Column('related_entity_id', sa.Integer(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_activity_category', 'user_activity_logs', ['activity_category'], unique=False)
    op.create_index('idx_user_activity_date', 'user_activity_logs', ['created_at'], unique=False)
    op.create_index('idx_user_activity_type', 'user_activity_logs', ['activity_type'], unique=False)
    op.create_index('idx_user_activity_user', 'user_activity_logs', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_activity_logs_activity_type'), 'user_activity_logs', ['activity_type'], unique=False)
    op.create_index(op.f('ix_user_activity_logs_created_at'), 'user_activity_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_user_activity_logs_id'), 'user_activity_logs', ['id'], unique=False)
    op.create_index(op.f('ix_user_activity_logs_user_id'), 'user_activity_logs', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_activity_logs_wallet_address'), 'user_activity_logs', ['wallet_address'], unique=False)
    op.create_table('user_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('wallet_address', sa.String(length=42), nullable=False),
    sa.Column('selected_protocol_id', sa.Integer(), nullable=True),
    sa.Column('auto_compound', sa.Boolean(), nullable=False),
    sa.Column('risk_tolerance', sa.Integer(), nullable=False),
    sa.Column('strategy_type', sa.Integer(), nullable=False),
    sa.Column('diversification_percent', sa.Integer(), nullable=False),
    sa.Column('rebalance_threshold', sa.Integer(), nullable=False),
    sa.Column('total_deposited', sa.DECIMAL(precision=18, scale=6), nullable=False),
    sa.Column('total_withdrawn', sa.DECIMAL(precision=18, scale=6), nullable=False),
    sa.Column('last_update', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('diversification_percent BETWEEN 0 AND 100', name='check_diversification_percent'),
    sa.CheckConstraint('risk_tolerance BETWEEN 1 AND 3', name='check_risk_tolerance'),
    sa.CheckConstraint('strategy_type BETWEEN 0 AND 3', name='check_strategy_type'),
    sa.ForeignKeyConstraint(['selected_protocol_id'], ['defi_protocols.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_preferences_strategy', 'user_preferences', ['strategy_type'], unique=False)
    op.create_index(op.f('ix_user_preferences_id'), 'user_preferences', ['id'], unique=False)
    op.create_index(op.f('ix_user_preferences_strategy_type'), 'user_preferences', ['strategy_type'], unique=False)
    op.create_index(op.f('ix_user_preferences_user_id'), 'user_preferences', ['user_id'], unique=True)
    op.create_index(op.f('ix_user_preferences_wallet_address'), 'user_preferences', ['wallet_address'], unique=False)
    op.create_table('user_protocol_deposits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('protocol_id', sa.Integer(), nullable=False),
    sa.Column('total_deposited', sa.DECIMAL(precision=18, scale=6), nullable=False),
    sa.Column('last_deposit_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['protocol_id'], ['defi_protocols.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'protocol_id', name='uq_user_protocol')
    )
    op.create_index('idx_user_protocol_deposits_protocol', 'user_protocol_deposits', ['protocol_id'], unique=False)
    op.create_index('idx_user_protocol_deposits_user', 'user_protocol_deposits', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_protocol_deposits_id'), 'user_protocol_deposits', ['id'], unique=False)
    op.create_index(op.f('ix_user_protocol_deposits_protocol_id'), 'user_protocol_deposits', ['protocol_id'], unique=False)
    op.create_index(op.f('ix_user_protocol_deposits_user_id'), 'user_protocol_deposits', ['user_id'], unique=False)
    op.create_table('voter_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('voter_address', sa.String(length=42), nullable=False),
    sa.Column('total_votes_cast', sa.Integer(), nullable=False),
    sa.Column('proposals_created', sa.Integer(), nullable=False),
    sa.Column('votes_for_count', sa.Integer(), nullable=False),
    sa.Column('votes_against_count', sa.Integer(), nullable=False),
    sa.Column('last_vote_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_proposal_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_voter_stats_address', 'voter_stats', ['voter_address'], unique=False)
    op.create_index('idx_voter_stats_user', 'voter_stats', ['user_id'], unique=False)
    op.create_index(op.f('ix_voter_stats_id'), 'voter_stats', ['id'], unique=False)
    op.create_index(op.f('ix_voter_stats_user_id'), 'voter_stats', ['user_id'], unique=True)
    op.create_index(op.f('ix_voter_stats_voter_address'), 'voter_stats', ['voter_address'], unique=False)
    op.create_table('votes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proposal_id', sa.Integer(), nullable=False),
    sa.Column('voter_id', sa.Integer(), nullable=False),
    sa.Column('voter_address', sa.String(length=42), nullable=False),
    sa.Column('support', sa.Boolean(), nullable=False),
    sa.Column('voting_power', sa.DECIMAL(precision=78, scale=18), nullable=False),
    sa.Column('transaction_hash', sa.String(length=66), nullable=False),
    sa.Column('block_number', sa.Integer(), nullable=False),
    sa.Column('block_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['voter_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('proposal_id', 'voter_id', name='uq_proposal_voter')
    )
    op.create_index(op.f('ix_votes_id'), 'votes', ['id'], unique=False)
    op.create_index(op.f('ix_votes_proposal_id'), 'votes', ['proposal_id'], unique=False)
    op.create_index(op.f('ix_votes_support'), 'votes', ['support'], unique=False)
    op.create_index(op.f('ix_votes_voter_id'), 'votes', ['voter_id'], unique=False)
    op.create_table('early_retirement_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fund_id', sa.Integer(), nullable=False),
    sa.Column('requester_id', sa.Integer(), nullable=False),
    sa.Column('fund_address', sa.String(length=42), nullable=False),
    sa.Column('requester_address', sa.String(length=42), nullable=False),
    sa.Column('proposal_id', sa.Integer(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('current_balance', sa.DECIMAL(precision=18, scale=6), nullable=True),
    sa.Column('penalty_amount', sa.DECIMAL(precision=18, scale=6), nullable=True),
    sa.Column('net_amount', sa.DECIMAL(precision=18, scale=6), nullable=True),
    sa.Column('approved', sa.Boolean(), nullable=False),
    sa.Column('rejected', sa.Boolean(), nullable=False),
    sa.Column('processed', sa.Boolean(), nullable=False),
    sa.Column('votes_for', sa.DECIMAL(precision=78, scale=18), nullable=False),
    sa.Column('votes_against', sa.DECIMAL(precision=78, scale=18), nullable=False),
    sa.Column('request_timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processed_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewer_address', sa.String(length=42), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('transaction_hash', sa.String(length=66), nullable=True),
    sa.ForeignKeyConstraint(['fund_id'], ['personal_funds.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_early_retirement_date', 'early_retirement_requests', ['request_timestamp'], unique=False)
    op.create_index('idx_early_retirement_fund', 'early_retirement_requests', ['fund_id'], unique=False)
    op.create_index('idx_early_retirement_processed', 'early_retirement_requests', ['processed'], unique=False)
    op.create_index(op.f('ix_early_retirement_requests_fund_address'), 'early_retirement_requests', ['fund_address'], unique=False)
    op.create_index(op.f('ix_early_retirement_requests_fund_id'), 'early_retirement_requests', ['fund_id'], unique=False)
    op.create_index(op.f('ix_early_retirement_requests_id'), 'early_retirement_requests', ['id'], unique=False)
    op.create_index(op.f('ix_early_retirement_requests_processed'), 'early_retirement_requests', ['processed'], unique=False)
    op.create_index(op.f('ix_early_retirement_requests_proposal_id'), 'early_retirement_requests', ['proposal_id'], unique=False)
    op.create_index(op.f('ix_early_retirement_requests_request_timestamp'), 'early_retirement_requests', ['request_timestamp'], unique=False)
    op.create_index(op.f('ix_early_retirement_requests_requester_address'), 'early_retirement_requests', ['requester_address'], unique=False)
    op.create_index(op.f('ix_early_retirement_requests_requester_id'), 'early_retirement_requests', ['requester_id'], unique=False)
    op.create_index(op.f('ix_early_retirement_requests_transaction_hash'), 'early_retirement_requests', ['transaction_hash'], unique=False)
    op.create_table('fund_fee_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fund_id', sa.Integer(), nullable=False),
    sa.Column('fund_address', sa.String(length=42), nullable=False),
    sa.Column('owner_address', sa.String(length=42), nullable=True),
    sa.Column('total_fees_paid', sa.DECIMAL(precision=18, scale=6), nullable=False),
    sa.Column('fee_count', sa.Integer(), nullable=False),
    sa.Column('last_fee_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('total_fees_paid >= 0', name='check_fees_paid_positive'),
    sa.ForeignKeyConstraint(['fund_id'], ['personal_funds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_fund_fee_records_address', 'fund_fee_records', ['fund_address'], unique=False)
    op.create_index('idx_fund_fee_records_fund', 'fund_fee_records', ['fund_id'], unique=False)
    op.create_index(op.f('ix_fund_fee_records_fund_address'), 'fund_fee_records', ['fund_address'], unique=False)
    op.create_index(op.f('ix_fund_fee_records_fund_id'), 'fund_fee_records', ['fund_id'], unique=False)
    op.create_index(op.f('ix_fund_fee_records_id'), 'fund_fee_records', ['id'], unique=False)
    op.create_index(op.f('ix_fund_fee_records_owner_address'), 'fund_fee_records', ['owner_address'], unique=False)
    op.create_table('fund_investments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fund_id', sa.Integer(), nullable=False),
    sa.Column('protocol_id', sa.Integer(), nullable=False),
    sa.Column('fund_address', sa.String(length=42), nullable=False),
    sa.Column('protocol_address', sa.String(length=42), nullable=False),
    sa.Column('amount_invested', sa.DECIMAL(precision=18, scale=6), nullable=False),
    sa.Column('current_balance', sa.DECIMAL(precision=18, scale=6), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('first_investment_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_update_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['fund_id'], ['personal_funds.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['protocol_id'], ['defi_protocols.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fund_investments_id'), 'fund_investments', ['id'], unique=False)
    op.create_index(op.f('ix_fund_investments_is_active'), 'fund_investments', ['is_active'], unique=False)
    op.create_table('fund_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fund_id', sa.Integer(), nullable=False),
    sa.Column('fund_address', sa.String(length=42), nullable=False),
    sa.Column('transaction_type', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.DECIMAL(precision=18, scale=6), nullable=False),
    sa.Column('balance_after', sa.DECIMAL(precision=18, scale=6), nullable=False),
    sa.Column('protocol_address', sa.String(length=42), nullable=True),
    sa.Column('protocol_name', sa.String(length=64), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('transaction_hash', sa.String(length=66), nullable=False),
    sa.Column('block_number', sa.Integer(), nullable=False),
    sa.Column('block_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('gas_used', sa.Integer(), nullable=True),
    sa.Column('gas_price', sa.DECIMAL(precision=18, scale=6), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fund_id'], ['personal_funds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transaction_hash', 'fund_address', name='uq_tx_fund')
    )
    op.create_index('idx_fund_transactions_date', 'fund_transactions', ['timestamp'], unique=False)
    op.create_index('idx_fund_transactions_fund', 'fund_transactions', ['fund_id'], unique=False)
    op.create_index('idx_fund_transactions_hash', 'fund_transactions', ['transaction_hash'], unique=False)
    op.create_index('idx_fund_transactions_type', 'fund_transactions', ['transaction_type'], unique=False)
    op.create_index(op.f('ix_fund_transactions_block_number'), 'fund_transactions', ['block_number'], unique=False)
    op.create_index(op.f('ix_fund_transactions_fund_address'), 'fund_transactions', ['fund_address'], unique=False)
    op.create_index(op.f('ix_fund_transactions_fund_id'), 'fund_transactions', ['fund_id'], unique=False)
    op.create_index(op.f('ix_fund_transactions_id'), 'fund_transactions', ['id'], unique=False)
    op.create_index(op.f('ix_fund_transactions_timestamp'), 'fund_transactions', ['timestamp'], unique=False)
    op.create_index(op.f('ix_fund_transactions_transaction_hash'), 'fund_transactions', ['transaction_hash'], unique=False)
    op.create_index(op.f('ix_fund_transactions_transaction_type'), 'fund_transactions', ['transaction_type'], unique=False)
    op.create_table('treasury_withdrawals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proposal_id', sa.Integer(), nullable=False),
    sa.Column('recipient_address', sa.String(length=42), nullable=False),
    sa.Column('amount', sa.DECIMAL(precision=18, scale=6), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=False),
    sa.Column('approved_by_governance', sa.Boolean(), nullable=False),
    sa.Column('executed', sa.Boolean(), nullable=False),
    sa.Column('transaction_hash', sa.String(length=66), nullable=True),
    sa.Column('block_number', sa.Integer(), nullable=True),
    sa.Column('requested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('amount > 0', name='check_withdrawal_amount_positive'),
    sa.ForeignKeyConstraint(['proposal_id'], ['proposals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_treasury_withdrawal_executed', 'treasury_withdrawals', ['executed'], unique=False)
    op.create_index('idx_treasury_withdrawal_proposal', 'treasury_withdrawals', ['proposal_id'], unique=False)
    op.create_index(op.f('ix_treasury_withdrawals_executed'), 'treasury_withdrawals', ['executed'], unique=False)
    op.create_index(op.f('ix_treasury_withdrawals_id'), 'treasury_withdrawals', ['id'], unique=False)
    op.create_index(op.f('ix_treasury_withdrawals_proposal_id'), 'treasury_withdrawals', ['proposal_id'], unique=False)
    op.create_index(op.f('ix_treasury_withdrawals_recipient_address'), 'treasury_withdrawals', ['recipient_address'], unique=False)
    op.create_index(op.f('ix_treasury_withdrawals_transaction_hash'), 'treasury_withdrawals', ['transaction_hash'], unique=False)
    op.add_column('faucet_requests', sa.Column('amount', sa.Numeric(precision=18, scale=6), nullable=True))
    op.execute("UPDATE faucet_requests SET amount = 100.000000 WHERE amount IS NULL")
    op.alter_column('faucet_requests', 'amount', nullable=False)
    op.add_column('faucet_requests', sa.Column('tx_hash', sa.String(length=66), nullable=True))
    op.add_column('faucet_requests', sa.Column('requested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('faucet_requests', sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('faucet_requests', sa.Column('user_agent', sa.Text(), nullable=True))
    op.drop_index(op.f('idx_created_at'), table_name='faucet_requests')
    op.drop_index(op.f('idx_wallet_address'), table_name='faucet_requests')
    op.drop_index(op.f('idx_wallet_status'), table_name='faucet_requests')
    op.create_index(op.f('ix_faucet_requests_id'), 'faucet_requests', ['id'], unique=False)
    op.create_index(op.f('ix_faucet_requests_tx_hash'), 'faucet_requests', ['tx_hash'], unique=False)
    op.create_index(op.f('ix_faucet_requests_wallet_address'), 'faucet_requests', ['wallet_address'], unique=False)
    op.drop_column('faucet_requests', 'initial_amount')
    op.drop_column('faucet_requests', 'desired_monthly_payment')
    op.drop_column('faucet_requests', 'usdc_transaction_hash')
    op.drop_column('faucet_requests', 'retirement_age')
    op.drop_column('faucet_requests', 'created_at')
    op.drop_column('faucet_requests', 'monthly_deposit')
    op.drop_column('faucet_requests', 'current_age')
    op.drop_column('faucet_requests', 'eth_transaction_hash')
    op.drop_column('faucet_requests', 'eth_amount_sent')
    op.drop_column('faucet_requests', 'contract_type')
    op.drop_column('faucet_requests', 'usdc_amount_sent')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('faucet_requests', sa.Column('usdc_amount_sent', sa.NUMERIC(precision=20, scale=6), autoincrement=False, nullable=True))
    op.add_column('faucet_requests', sa.Column('contract_type', sa.VARCHAR(length=20), server_default=sa.text("'mock'::character varying"), autoincrement=False, nullable=True))
    op.add_column('faucet_requests', sa.Column('eth_amount_sent', sa.NUMERIC(precision=20, scale=10), autoincrement=False, nullable=True))
    op.add_column('faucet_requests', sa.Column('eth_transaction_hash', sa.VARCHAR(length=66), autoincrement=False, nullable=True))
    op.add_column('faucet_requests', sa.Column('current_age', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('faucet_requests', sa.Column('monthly_deposit', sa.NUMERIC(precision=20, scale=2), autoincrement=False, nullable=False))
    op.add_column('faucet_requests', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('faucet_requests', sa.Column('retirement_age', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('faucet_requests', sa.Column('usdc_transaction_hash', sa.VARCHAR(length=66), autoincrement=False, nullable=True))
    op.add_column('faucet_requests', sa.Column('desired_monthly_payment', sa.NUMERIC(precision=20, scale=2), autoincrement=False, nullable=False))
    op.add_column('faucet_requests', sa.Column('initial_amount', sa.NUMERIC(precision=20, scale=2), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_faucet_requests_wallet_address'), table_name='faucet_requests')
    op.drop_index(op.f('ix_faucet_requests_tx_hash'), table_name='faucet_requests')
    op.drop_index(op.f('ix_faucet_requests_id'), table_name='faucet_requests')
    op.create_index(op.f('idx_wallet_status'), 'faucet_requests', ['status'], unique=False)
    op.create_index(op.f('idx_wallet_address'), 'faucet_requests', ['wallet_address'], unique=False)
    op.create_index(op.f('idx_created_at'), 'faucet_requests', ['created_at'], unique=False)
    op.drop_column('faucet_requests', 'user_agent')
    op.drop_column('faucet_requests', 'processed_at')
    op.drop_column('faucet_requests', 'requested_at')
    op.drop_column('faucet_requests', 'tx_hash')
    op.drop_column('faucet_requests', 'amount')
    op.drop_index(op.f('ix_treasury_withdrawals_transaction_hash'), table_name='treasury_withdrawals')
    op.drop_index(op.f('ix_treasury_withdrawals_recipient_address'), table_name='treasury_withdrawals')
    op.drop_index(op.f('ix_treasury_withdrawals_proposal_id'), table_name='treasury_withdrawals')
    op.drop_index(op.f('ix_treasury_withdrawals_id'), table_name='treasury_withdrawals')
    op.drop_index(op.f('ix_treasury_withdrawals_executed'), table_name='treasury_withdrawals')
    op.drop_index('idx_treasury_withdrawal_proposal', table_name='treasury_withdrawals')
    op.drop_index('idx_treasury_withdrawal_executed', table_name='treasury_withdrawals')
    op.drop_table('treasury_withdrawals')
    op.drop_index(op.f('ix_fund_transactions_transaction_type'), table_name='fund_transactions')
    op.drop_index(op.f('ix_fund_transactions_transaction_hash'), table_name='fund_transactions')
    op.drop_index(op.f('ix_fund_transactions_timestamp'), table_name='fund_transactions')
    op.drop_index(op.f('ix_fund_transactions_id'), table_name='fund_transactions')
    op.drop_index(op.f('ix_fund_transactions_fund_id'), table_name='fund_transactions')
    op.drop_index(op.f('ix_fund_transactions_fund_address'), table_name='fund_transactions')
    op.drop_index(op.f('ix_fund_transactions_block_number'), table_name='fund_transactions')
    op.drop_index('idx_fund_transactions_type', table_name='fund_transactions')
    op.drop_index('idx_fund_transactions_hash', table_name='fund_transactions')
    op.drop_index('idx_fund_transactions_fund', table_name='fund_transactions')
    op.drop_index('idx_fund_transactions_date', table_name='fund_transactions')
    op.drop_table('fund_transactions')
    op.drop_index(op.f('ix_fund_investments_is_active'), table_name='fund_investments')
    op.drop_index(op.f('ix_fund_investments_id'), table_name='fund_investments')
    op.drop_table('fund_investments')
    op.drop_index(op.f('ix_fund_fee_records_owner_address'), table_name='fund_fee_records')
    op.drop_index(op.f('ix_fund_fee_records_id'), table_name='fund_fee_records')
    op.drop_index(op.f('ix_fund_fee_records_fund_id'), table_name='fund_fee_records')
    op.drop_index(op.f('ix_fund_fee_records_fund_address'), table_name='fund_fee_records')
    op.drop_index('idx_fund_fee_records_fund', table_name='fund_fee_records')
    op.drop_index('idx_fund_fee_records_address', table_name='fund_fee_records')
    op.drop_table('fund_fee_records')
    op.drop_index(op.f('ix_early_retirement_requests_transaction_hash'), table_name='early_retirement_requests')
    op.drop_index(op.f('ix_early_retirement_requests_requester_id'), table_name='early_retirement_requests')
    op.drop_index(op.f('ix_early_retirement_requests_requester_address'), table_name='early_retirement_requests')
    op.drop_index(op.f('ix_early_retirement_requests_request_timestamp'), table_name='early_retirement_requests')
    op.drop_index(op.f('ix_early_retirement_requests_proposal_id'), table_name='early_retirement_requests')
    op.drop_index(op.f('ix_early_retirement_requests_processed'), table_name='early_retirement_requests')
    op.drop_index(op.f('ix_early_retirement_requests_id'), table_name='early_retirement_requests')
    op.drop_index(op.f('ix_early_retirement_requests_fund_id'), table_name='early_retirement_requests')
    op.drop_index(op.f('ix_early_retirement_requests_fund_address'), table_name='early_retirement_requests')
    op.drop_index('idx_early_retirement_processed', table_name='early_retirement_requests')
    op.drop_index('idx_early_retirement_fund', table_name='early_retirement_requests')
    op.drop_index('idx_early_retirement_date', table_name='early_retirement_requests')
    op.drop_table('early_retirement_requests')
    op.drop_index(op.f('ix_votes_voter_id'), table_name='votes')
    op.drop_index(op.f('ix_votes_support'), table_name='votes')
    op.drop_index(op.f('ix_votes_proposal_id'), table_name='votes')
    op.drop_index(op.f('ix_votes_id'), table_name='votes')
    op.drop_table('votes')
    op.drop_index(op.f('ix_voter_stats_voter_address'), table_name='voter_stats')
    op.drop_index(op.f('ix_voter_stats_user_id'), table_name='voter_stats')
    op.drop_index(op.f('ix_voter_stats_id'), table_name='voter_stats')
    op.drop_index('idx_voter_stats_user', table_name='voter_stats')
    op.drop_index('idx_voter_stats_address', table_name='voter_stats')
    op.drop_table('voter_stats')
    op.drop_index(op.f('ix_user_protocol_deposits_user_id'), table_name='user_protocol_deposits')
    op.drop_index(op.f('ix_user_protocol_deposits_protocol_id'), table_name='user_protocol_deposits')
    op.drop_index(op.f('ix_user_protocol_deposits_id'), table_name='user_protocol_deposits')
    op.drop_index('idx_user_protocol_deposits_user', table_name='user_protocol_deposits')
    op.drop_index('idx_user_protocol_deposits_protocol', table_name='user_protocol_deposits')
    op.drop_table('user_protocol_deposits')
    op.drop_index(op.f('ix_user_preferences_wallet_address'), table_name='user_preferences')
    op.drop_index(op.f('ix_user_preferences_user_id'), table_name='user_preferences')
    op.drop_index(op.f('ix_user_preferences_strategy_type'), table_name='user_preferences')
    op.drop_index(op.f('ix_user_preferences_id'), table_name='user_preferences')
    op.drop_index('idx_user_preferences_strategy', table_name='user_preferences')
    op.drop_table('user_preferences')
    op.drop_index(op.f('ix_user_activity_logs_wallet_address'), table_name='user_activity_logs')
    op.drop_index(op.f('ix_user_activity_logs_user_id'), table_name='user_activity_logs')
    op.drop_index(op.f('ix_user_activity_logs_id'), table_name='user_activity_logs')
    op.drop_index(op.f('ix_user_activity_logs_created_at'), table_name='user_activity_logs')
    op.drop_index(op.f('ix_user_activity_logs_activity_type'), table_name='user_activity_logs')
    op.drop_index('idx_user_activity_user', table_name='user_activity_logs')
    op.drop_index('idx_user_activity_type', table_name='user_activity_logs')
    op.drop_index('idx_user_activity_date', table_name='user_activity_logs')
    op.drop_index('idx_user_activity_category', table_name='user_activity_logs')
    op.drop_table('user_activity_logs')
    op.drop_index(op.f('ix_token_holders_wallet_address'), table_name='token_holders')
    op.drop_index(op.f('ix_token_holders_is_active'), table_name='token_holders')
    op.drop_index(op.f('ix_token_holders_id'), table_name='token_holders')
    op.drop_index(op.f('ix_token_holders_has_activity_this_month'), table_name='token_holders')
    op.drop_table('token_holders')
    op.drop_index(op.f('ix_token_activities_user_id'), table_name='token_activities')
    op.drop_index(op.f('ix_token_activities_id'), table_name='token_activities')
    op.drop_index(op.f('ix_token_activities_created_at'), table_name='token_activities')
    op.drop_index(op.f('ix_token_activities_activity_type'), table_name='token_activities')
    op.drop_table('token_activities')
    op.drop_index(op.f('ix_proposals_start_time'), table_name='proposals')
    op.drop_index(op.f('ix_proposals_proposer_address'), table_name='proposals')
    op.drop_index(op.f('ix_proposals_proposal_type'), table_name='proposals')
    op.drop_index(op.f('ix_proposals_proposal_id'), table_name='proposals')
    op.drop_index(op.f('ix_proposals_id'), table_name='proposals')
    op.drop_index(op.f('ix_proposals_executed'), table_name='proposals')
    op.drop_index(op.f('ix_proposals_end_time'), table_name='proposals')
    op.drop_index(op.f('ix_proposals_cancelled'), table_name='proposals')
    op.drop_table('proposals')
    op.drop_index(op.f('ix_personal_funds_retirement_started'), table_name='personal_funds')
    op.drop_index(op.f('ix_personal_funds_owner_id'), table_name='personal_funds')
    op.drop_index(op.f('ix_personal_funds_owner_address'), table_name='personal_funds')
    op.drop_index(op.f('ix_personal_funds_is_active'), table_name='personal_funds')
    op.drop_index(op.f('ix_personal_funds_id'), table_name='personal_funds')
    op.drop_index(op.f('ix_personal_funds_fund_address'), table_name='personal_funds')
    op.drop_index('idx_personal_funds_retirement', table_name='personal_funds')
    op.drop_index('idx_personal_funds_owner', table_name='personal_funds')
    op.drop_index('idx_personal_funds_address', table_name='personal_funds')
    op.drop_index('idx_personal_funds_active', table_name='personal_funds')
    op.drop_table('personal_funds')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_read'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_index('idx_notifications_unread', table_name='notifications', postgresql_where=sa.text('read = false'))
    op.drop_table('notifications')
    op.drop_index(op.f('ix_weekly_reports_year'), table_name='weekly_reports')
    op.drop_index(op.f('ix_weekly_reports_week_number'), table_name='weekly_reports')
    op.drop_index(op.f('ix_weekly_reports_id'), table_name='weekly_reports')
    op.drop_index('idx_weekly_reports_date', table_name='weekly_reports')
    op.drop_table('weekly_reports')
    op.drop_index(op.f('ix_treasury_stats_last_updated'), table_name='treasury_stats')
    op.drop_index(op.f('ix_treasury_stats_id'), table_name='treasury_stats')
    op.drop_index('idx_treasury_stats_updated', table_name='treasury_stats')
    op.drop_table('treasury_stats')
    op.drop_index(op.f('ix_token_monthly_stats_year'), table_name='token_monthly_stats')
    op.drop_index(op.f('ix_token_monthly_stats_month'), table_name='token_monthly_stats')
    op.drop_index(op.f('ix_token_monthly_stats_id'), table_name='token_monthly_stats')
    op.drop_index('idx_year_month', table_name='token_monthly_stats')
    op.drop_table('token_monthly_stats')
    op.drop_index(op.f('ix_system_metrics_metric_name'), table_name='system_metrics')
    op.drop_index(op.f('ix_system_metrics_last_updated'), table_name='system_metrics')
    op.drop_index(op.f('ix_system_metrics_id'), table_name='system_metrics')
    op.drop_index('idx_system_metrics_updated', table_name='system_metrics')
    op.drop_index('idx_system_metrics_name', table_name='system_metrics')
    op.drop_table('system_metrics')
    op.drop_index(op.f('ix_monthly_reports_year'), table_name='monthly_reports')
    op.drop_index(op.f('ix_monthly_reports_month'), table_name='monthly_reports')
    op.drop_index(op.f('ix_monthly_reports_id'), table_name='monthly_reports')
    op.drop_index('idx_monthly_reports_date', table_name='monthly_reports')
    op.drop_table('monthly_reports')
    op.drop_index(op.f('ix_defi_protocols_verified'), table_name='defi_protocols')
    op.drop_index(op.f('ix_defi_protocols_protocol_address'), table_name='defi_protocols')
    op.drop_index(op.f('ix_defi_protocols_is_active'), table_name='defi_protocols')
    op.drop_index(op.f('ix_defi_protocols_id'), table_name='defi_protocols')
    op.drop_table('defi_protocols')
    op.drop_index(op.f('ix_daily_snapshots_snapshot_date'), table_name='daily_snapshots')
    op.drop_index(op.f('ix_daily_snapshots_id'), table_name='daily_snapshots')
    op.drop_index('idx_daily_snapshots_date', table_name='daily_snapshots', postgresql_using='btree')
    op.drop_table('daily_snapshots')
    op.drop_index(op.f('ix_blockchain_events_processed'), table_name='blockchain_events')
    op.drop_index(op.f('ix_blockchain_events_id'), table_name='blockchain_events')
    op.drop_index(op.f('ix_blockchain_events_event_type'), table_name='blockchain_events')
    op.drop_index(op.f('ix_blockchain_events_contract_address'), table_name='blockchain_events')
    op.drop_index(op.f('ix_blockchain_events_block_number'), table_name='blockchain_events')
    op.drop_table('blockchain_events')
    # ### end Alembic commands ###
